### PR TITLE
Issue #1: `useCallback` in `useEmit`

### PR DESCRIPTION
**Pull request by franleplant**
Hi! This is the patch fixing the return callback on `useEmit`. [ref](https://github.com/ghmendonca/socketio-hooks/issues/1)

I tested this in the current private app I am working on that already uses this lib and everything seems fine.

While I was there I tweaked a couple of things. I know this might be me overstepping so if you don't like my changes then I can simply strip out the `useEmit` thing and move on.

However I do think these changes are for the better
- Added `CHANGELOG.md`: this is a good precedent for this good library, starting to document the changes in a more structured and human friendly way will be a big plus for our users
- use `useNamespace` across all the hooks to remove duplicated logic. I was meaning to write something very similar to `useNamespace` when I notice you already have written it! so it was a matter of simply using the already existing hook in order to reduce the amount of code duplication in the lib. This did make the hooks much more simpler and in the case of `useEmit` it became a very thin hook.
- rename the anonymous-inline return type of `useEmit` to a named type.

Further comments about the lib
- `tslint` is kind of deprecated and I noticed that simple things such as unused variables weren't caught by the current setup. We might want to spend some time improving on this.
- `tests`. We currently dont have tests nor test infra, it would be nice to start working towards that.
- `prettier config`: I notice you have set prettier to use 120 char long lines, that is usually a bad idea since long lines tend to be difficult to understand. Would you consider using the default 80 char length? What is the reasoning behind using 120?
- `peerDependencies`: react, @types/react, and probably socket.io-client and @types/socket.io-client should be peerDependencies (usually you specify them as peerDependencies and as devDependencies).
- `automation`: we can setup github actions to run tests, lints, etc and then to publish new versions automatically

All of these could be expressed in the form of issues in the repo to help us track them and even to help others wanting to contribute to have ready to take "stories".

Thanks!
Fran

PS: I will be out a couple of days

### CODE REVIEW

**Comment by ghmendonca** [comment]
Thanks so much for this message!

- tslint: about that, I'm not used to configure these things, so I basically took from another project that was already running, probably this is not the best configuration and you're welcome to change!
- tests: this is something that I want but I never worked with tests in React, so I'm not sure how to do this and automate this with github, to be honest I'm new to the open source world, this is my first library and I would be happy to learn these things to improve this lib :)

Awesome feedback, I really appreciate and I'll try to improve these topics you mentioned in the next week.

**Comment by franleplant** [comment]
I might be able to help you with all these things, I have experience with
all of them, so you’ll be hearing from me.

Please dont forget to publish a new version

**Comment by franleplant** [comment]
@ghmendonca can you please publish version 0.0.6 ?

**Comment by ghmendonca** [comment]
@franleplant sorry, I thought I already did lol.. It's available now, thanks man

**Comment by franleplant** [comment]
thank you!

**Pull request merged**
